### ISSUE TITLE
common concepts

### ISSUE THREAD

**Issue by Yuqifan1117** [Davidzhangyuanhan/Bamboo#8]
Great work.
Where can I access the 809 common concepts mentioned in the paper? The 'id2name' in the label system has 304048 concepts, while i am more interested in those 809 common concepts. Hope you can help me!

**Comment by ZhangYuanhan-AI** [comment]
Checkout bamboo['id2state'][id] 
0, not common, 1 common, 2 unknow

**Comment by Yuqifan1117** [comment]
however, i use 'if bamboo_data['id2state'][k]['common'] == 1 and bamboo_data['id2state'][k]['visual'] == 1' to figure out common categories, however got the number of 3582 but not 809. Is there any wrong?

**Comment by ZhangYuanhan-AI** [comment]
Check out the label2tag.json in the unzipped file of "https://shorturl.at/npzCM".

**Comment by Yuqifan1117** [comment]
Thanks! I check out the label2tag.json and find 747 categories. Is this all the categories used in bamboo-det? (v.s. 809) 
What is the difference between this and bamboo['id2name'][id]? Is the latter used for all categories of **Bamboo-CLS**?

**Comment by ZhangYuanhan-AI** [comment]
1. Yes, the 747 categories are the newest version of the bamboo-det.
2. 747 is the subset of common labels, 
3. no, part of the ids are used for Bamboo-CLS?

**Comment by Yuqifan1117** [comment]
I have completely understood. Thank you very much for resolving my question very quickly!

**Comment by ZhangYuanhan-AI** [comment]
> I have completely understood. Thank you very much for resolving my question very quickly!

Enjoy bamboo.
